name: txstcsstudentguide CI/CD

on:
  push:
    branches: [ production ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run:
        npm i
        cd frontend
        npm i
        npm run build
