name: txstcsstudentguide CI/CD

on:
  push:
    branches: [ production ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14.17.0
    - run: npm i
    - run: npm run build
    - run: pm2 stop 0
    - run: pm2 start 0
    - run: pm2 save
    - run: sudo service nginx restart
